### ISSUE TITLE
How OASIS+ Compares updates

### ISSUE THREAD

**Issue by rosamundtgov** [GSA/oasis-plus#244]
Bucket for updates on https://docs.google.com/document/d/1TOzw0xzxMmnvWgBnEZpbMSCGpMPDSnVX1vMk0q8liOE/edit as a result of the ordering guide review. Updates are highlighted green in the document.

**Comment by klohman** [comment]
Updates to the How OASIS+ compares table to be tracked in #198 . Closing this as duplicate.
