### ISSUE TITLE
Favicon links are broken

### ISSUE THREAD

**Issue by jfredrickson** [GSA/oasis-plus#272]
Favicon links in `head` do not exist:

* images/favicon-16x16.png
* images/favicon-32x32.png

**Comment by jfredrickson** [comment]
For design review, let me know if these favicons look right:

![gsa logo](https://raw.githubusercontent.com/GSA/oasis-plus/staging/public/images/favicon-16x16.png)
![gsa logo](https://raw.githubusercontent.com/GSA/oasis-plus/staging/public/images/favicon-32x32.png)

**Comment by klohman** [comment]
> For design review, let me know if these favicons look right:
> 
> ![gsa logo](https://raw.githubusercontent.com/GSA/oasis-plus/staging/public/images/favicon-16x16.png) ![gsa logo](https://raw.githubusercontent.com/GSA/oasis-plus/staging/public/images/favicon-32x32.png)

@jfredrickson The favicons look right. Have they been implemented on the demo site?

**Comment by jfredrickson** [comment]
@klohman yup, they should be there.

**Comment by klohman** [comment]
@jfredrickson I am not seeing it for https://federalist-76c8d2ee-2655-47f7-8fa4-63811842d0a5.sites.pages.cloud.gov/demo/gsa/oasis-plus/

<img width="243" alt="Screenshot 2024-03-14 at 8 18 02 AM" src="https://github.com/GSA/oasis-plus/assets/18366192/376c965d-fd59-4efa-b311-0fbb4ae9de2d">

**Comment by klohman** [comment]
@ekidenda @PowderD This is ready for your review. https://federalist-76c8d2ee-2655-47f7-8fa4-63811842d0a5.sites.pages.cloud.gov/demo/gsa/oasis-plus/

(Note: the favicon is the GSA icon that appears in your browser tab.

![Image](https://github.com/GSA/oasis-plus/assets/18366192/d1dc2239-3086-4e4c-800e-9d437d8fc33a)

**Comment by ekidenda** [comment]
The favicon display on all tabs while browsing through all pages. Looks good and moving this to done.
