### ISSUE TITLE
Release 2 usability testing

### ISSUE THREAD

**Issue by klohman** [GSA/oasis-plus#333]
Conduct usability testing on release 2 content

- [x] Develop usability test plan ([draft](https://docs.google.com/document/d/1i0jLMHkendwEsJ7VxR_iQ9o06pGaNW4oKQ6uBXkYvBw/edit#heading=h.r9nbj795zr0k))
- [ ] Recruit participants [(participant tracking)](https://docs.google.com/spreadsheets/d/1c0n82aWXUoJGiAd1NOIbIouHKyeknKMBn3fnS4A-uSY/edit#gid=194099130)
- [ ] Conduct test sessions 
- [ ] Analysis 
- [ ] Report delivered to PSHC and backlog items created

**Comment by klohman** [comment]
@ekidenda @PowderD @smteague 

I've updated the [Release 2 Usability Test Plan](https://docs.google.com/document/d/1i0jLMHkendwEsJ7VxR_iQ9o06pGaNW4oKQ6uBXkYvBw/edit#heading=h.momj4czhzxm2) with the updated scope. Please review and comment if you have any edits to the proposed tasks. 

Since Release 2 will focus on the Sellers guide, I recommend recruiting participants from the seller community only. We have a number of possible recruits who were interested in participating that I plan to reach out to once we have a better idea on when the pages will be ready to test. For now, I'm going to put this on hold.

**Comment by PowderD** [comment]
The seller recruits can be industry partners correct?

*Jon DeWolfe  |  *
Program Manager Buyer Engagement
Services Marketplace
Federal Acquisition Service, U.S. General Services Administration
|(: 208.830.8517 | *: ***@***.***

**Comment by klohman** [comment]
Holding on usability until future release with full ordering guide - and will include these updates to that testing.
